-- phpMyAdmin SQL Dump
-- version 4.7.9
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Gegenereerd op: 23 jan 2019 om 13:17
-- Serverversie: 10.1.31-MariaDB
-- PHP-versie: 7.2.3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `havenstad`
--

-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `articles`
--

CREATE TABLE `articles` (
  `id` int(11) NOT NULL,
  `category` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `date` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `text` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `textorimage` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `source` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `texthavenstad` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `titlehavenstad` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sourcelogo` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Gegevens worden geëxporteerd voor tabel `articles`
--

INSERT INTO `articles` (`id`, `category`, `date`, `title`, `text`, `textorimage`, `source`, `texthavenstad`, `titlehavenstad`, `sourcelogo`) VALUES
(10, 'mobiliteit', '3-1-2018', '“Verdere vertraging bij bouw Tesla Model 3\"', 'Tesla heeft een productiedoelstelling van zijn Model 3 verder voor zich uitgeschoven. De maker van elektrische auto’s denkt nu niet eerder dan halverwege dit jaar 5000 wagens per week te kunnen afleveren van het type. Tesla Model 3 is de nieuwe auto die door Tesla in juli is geïntroduceerd als de elektrische auto voor de massa. ', '3jan.jpg', 'https://www.telegraaf.nl/financieel/1499850/verdere-vertraging-bij-bouw-tesla-model-3', 'Haven-Stad stimuleert het rijden in elektrische auto’s, in 2018 moet in Haven-Stad van de 1000 oplaadpunten gegaan worden naar de 4000 oplaadpunten. Tesla is bezig met het ontwikkelen van elektrische auto’s. Er komen steeds meer elektrische auto’s, deze groei zal in de toekomst van Haven-Stad zorgen voor een bewust milieubeeld.', '\"Er komen steeds meer elektrische auto’s, in Haven-Stad zorgt het voor een bewust milieubeeld\"', 'telegraaf.png'),
(11, 'leven', '1-1-2018', '“Nederland is dit jaar tijdelijk lid van Veiligheidsraad”', 'Voor de zesde keer sinds 1946 is Nederland tijdelijk lid van de Veiligheidsraad van de Verenigde Naties. Nederland neemt het stokje over van Italië. De veiligheidsraad is het belangrijkste orgaan van de VN op het gebied van vrede en veiligheid.  De raad kan onder meer sancties opleggen en vredestroepen (blauwhelmen) inzetten.', '1jan.jpg', 'https://www.trouw.nl/home/nederland-is-dit-jaar-tijdelijk-lid-van-veiligheidsraad~ac923e4f/', 'Haven-Stad gaat in de toekomst zorgen voor een prettige en veilige leefomgeving. De veiligheid in Haven-Stad zorgt voor de gezondheid van de inwoners en zal milieutechnische en economische voordelen hebben. Om de veiligheid in Haven-Stad te waarborgen worden er waar nodig aanpassingen gedaan in de bestemmingsplannen. In 2040 zal Haven-Stad een vredige en veilige plek zijn voor bewoners, werkenden en bezoekers in de stad.', '\"Haven-Stad gaat in de toekomst zorgen voor een prettige en veilige leefomgeving\"', 'trouw.png'),
(12, 'leven', '2-1-2018', '“België krijgt digitaal patiëntendossier”', 'De Belgen kunnen binnenkort hun eigen medische dossier via het internet in kijken. Het digitaal platform Personal Health Viewer wordt in het eerste kwartaal van dit jaar gelanceerd, volgens Maggie De Block. De Belgen krijgen de mogelijkheid om zaken toe te voegen die er volgens de patiënt ook bij moeten staan, ook mogen de Belgen kiezen of hun dossier met anderen gedeeld kunnen worden. De Block hoopt dat het platform mensen stimuleert meer met hun gezondheid bezig te zijn.', '2jan.jpg', 'https://www.telegraaf.nl/nieuws/1495233/belgie-krijgt-digitaal-patientendossier', 'Haven-Stad wil er in de toekomst voor zorgen dat er een gezonde leefomgeving is en dat de gezondheid wordt bevorderd. De gezondheid in Haven-Stad wordt bevorderd door gezond gedrag, er wordt veel gesport, er zijn rookvrije speel- en sportvoorzieningen en gezonde voeding (snackbarvrije zone rondom scholen) is erg belangrijk. Het project in België wil bewoners stimuleren om meer met hun gezondheid bezig te zijn, hieraan neemt Haven-Stad een voorbeeld. ', '\"Haven-Stad wil er in de toekomst voor zorgen dat er een gezonde leefomgeving is\"', 'telegraaf.png'),
(13, 'wonen', '4-1-2018', '“Woningmarkt 2018 nog krapper, maar geen paniek”', 'Dit jaar krijgen we te maken met een nog krappere woningmarkt. Er worden minder woningen te koop gezet, er wordt hoger geboden en prijzen stijgen. Het verschil tussen vraag- en biedprijs wordt steeds kleiner, constateert ABN Amro in de eerste Woningmarktmonitor van 2018. Dit gaat vaak gepaard met verdere prijsstijgingen, die kunnen op den duur te groot worden als bijvoorbeeld de hypotheekrente stijgt of als het aanbod woningen wordt aangevuld met nieuwbouw. ', '4jan.jpg', 'https://www.telegraaf.nl/financieel/1502145/woningmarkt-2018-nog-krapper-maar-geen-paniek ', 'In project Haven-Stad worden er vaak aanpassingen gedaan op basis van nieuwe inzichten en ontwikkelingen ten opzichte van 2013. De druk op de Amsterdamse woningmarkt neemt toe. De afgelopen tijd is er onderzoek gedaan naar de hoge dichtheden voor het wonen en werken in Haven-Stad. De transformatiestrategie van Haven-Stad laat zien dat er tussen de 40.000 en 70.000 woningen en 45.000 tot 58.000 arbeidsplaatsen gebouwd kunnen worden. Haven-Stad gaat in tegen de krappe woningmarkt!', '\"Haven-Stad gaat in tegen de krappe woningmarkt!\"', 'telegraaf.png'),
(14, 'duurzaamheid', '23-1-2018', '“Gezondheidsraad wil dat overheid meer doet voor schonere lucht”', 'Het kabinet moet meer maatregelen nemen om de luchtkwaliteit in Nederland te verbeteren. Dat schrijft de Gezondheidsraad dinsdag in een advies over dit onderwerp. Luchtverontreiniging levert nog steeds een belangrijke bijdrage aan ziekte en sterfte in Nederland. Het zou prioriteit moeten hebben van de overheid om de concentraties fijnstof en stikstofdioxide afkomstig van het wegverkeer terug te dringen. Vooral dieselvoertuigen zouden sneller van de weg moeten verdwijnen.', '23jan.jpg', 'https://www.nu.nl/klimaat/5099663/gezondheidsraad-wil-overheid-meer-doet-schonere-lucht.html ', 'Haven-Stad is het eens met de verbetering van de luchtkwaliteit. In 2025 moet er 30% minder uitstoot van roet zijn en 35% minder uitstoot van stikstofdioxide. Dit moet gedaan worden door slim en schoon vervoer te stimuleren, een voorbeeld hiervan is het niet meer geven van parkeervergunningen voor te oude auto’s en de bussen die in 2026 uitstootvrij moeten zijn. Zo gaat Haven-Stad op weg naar schonere lucht.', '\"Haven-Stad is het eens met de verbetering van de luchtkwaliteit\"', 'nu.png'),
(15, 'wonen', '25-1-2018', '“Krachtige groei infrastructuur”', 'De bouwproductie is in 2017 opnieuw sterk gegroeid. De groei werd vooral gedragen door de investeringen in de woningbouw, die met 10% is toegenomen. De groei zal de komende twee jaar hoog blijven. De groei in de woningbouw vlakt duidelijk af, terwijl de investeringen in infrastructuur juist sterk toenemen. Daarmee wordt de infrastructuur de belangrijkste groeisector binnen de bouw in de komende twee jaar. ', '25jan.jpg', 'https://www.eib.nl/nieuws/krachtige-groei-infrastructuur/', 'In Haven-Stad worden gebouwen vernieuwd of nieuw gebouwd, er worden openbare ruimtes aangepast en infrastructuren voor water, energie en afval vernieuwd. Haven-Stad is de duurzame stad van morgen. De groei van de infrastructuur is ook te zien in Haven-Stad. In Haven-Stad wordt er bezig gegaan met het water, het openbaar vervoer, fietsers en voetgangers, de auto en er wordt rekening gehouden met de bedrijven. Kortom niet alleen de woningbouw neemt toe in Haven-Stad, maar ook de infrastructuur.', '\"Kortom niet alleen de woningbouw neemt toe in Haven-Stad, maar ook de infrastructuur\"', 'eib.png'),
(16, 'leven', '27-1-2018', '“Leeuwarden nu echt Culturele Hoofdstad”', 'Leeuwarden mag dan Culturele Hoofdstad van Europa zijn geworden, heel Friesland werkt mee. De provincie zal dit jaar 250 culturele evenementen herbergen, opgezet vanuit zestig professionele initiatieven. ', '27jan.jpg', 'https://www.ad.nl/binnenland/leeuwarden-nu-eneacute-cht-culturele-hoofdstad~a1e87e90/', 'Haven-Stad wil net als in Leeuwarden veel cultuur behouden en hierdoor het nieuwe gebied extra oplichten. In Haven-Stad zullen de cultuurhistorische elementen zoveel mogelijk gebruikt worden. Het IJ is één van de belangrijkste onderdelen in de geschiedenis van Haven-Stad en is belangrijk in de ontwikkeling van Amsterdam tot een boeiende en toonaangevende hoofdstad van Nederland. ', '\"In Haven-Stad zullen de cultuurhistorische elementen zoveel mogelijk gebruikt worden\"', 'ad.png'),
(17, 'duurzaamheid', '30-1-2018', '“Omschakeling naar duurzame warmte voor veel huiseigenaren te duur”', 'De omschakeling van gas naar duurzame warmte is voor veel huiseigenaren niet te betalen. Dat blijkt uit een onderzoek dat Milieudefensie heeft laten verrichten. Daarom zou de overheid bij moeten springen, stelt de milieuclub. “Huiseigenaren kunnen zich niet altijd een warmtepomp of een goed geïsoleerd huis veroorloven, zelf als ze dat graag zouden willen. Mensen met minder geld kunnen daardoor in de problemen raken. Dat vinden wij niet eerlijk”, stelt Donald Pols, directeur van Milieudefensie.', '30jan.jpg', 'https://www.nu.nl/wonen/5109614/omschakeling-duurzame-warmte-veel-huiseigenaren-duur.html', 'In Haven-Stad moet er van 62.000 woningen naar 102.000 woningen gegaan worden als het gaat over het aansluiten op de stadswarmte. Haven-Stad wil energiezuinige gebouwen gaan bouwen en hierdoor warmte- en koudevoorzieningen laten verduurzamen, dit helpt daarnaast ook mee aan het verminderen van de CO2-uitstoot. Door de minimale ruimte om duurzame elektriciteit op te wekken ligt de focus in Haven-Stad juist op de duurzame warmte- en koudevoorzieningen.', '\"Haven-Stad wil energiezuinige gebouwen gaan bouwen\"', 'nu.png'),
(18, 'mobiliteit', '5-2-2018', '“Spaarndammertunnel opengesteld voor verkeer”', 'Op 5 februari is de Spaarndammertunnel opengesteld voor verkeer. De Spaarndammertunnel brengt daarmee doorgaand verkeer van en naar Amsterdam-centrum ondergronds. Bovengronds ontstaat hierdoor een mooi park dat de bestaande Spaarndammerbuurt met de nieuwe woonwijk Houthaven verbindt. Een bijzondere gegeven is dat de tunnel gerealiseerd is in de Spaarndammerdijk, een primaire waterkering. ', '5feb.jpg', 'https://www.anteagroup.nl/nl/nieuws/spaarndammertunnel-opengesteld-voor-verkeer', 'De Spaarndammertunnel heeft een grote betekenis voor Haven-Stad. De Spaarndammertunnel is een tunnel voor het autoverkeer in Amsterdam-West, de tunnel zal in de toekomst zorgen voor veel mobiliteit en goede bereikbaarheid in de nieuwe wijken.', '\"De Spaarndammertunnel heeft een grote betekenis voor Haven-Stad\"', 'antea.png'),
(19, 'leven', '9-2-2018', '“Winterspelen in Pyeongchang geopend”', 'De 23e editie van de Olympische Winterspelen is vrijdag officieel geopend met een ceremonie in het olympisch stadion van Pyeongchang.', '9feb.jpg', 'https://www.nu.nl/olympische-winterspelen-pyeongchang-2018/5126060/winterspelen-in-pyeongchang-geopend.html', 'Mensen worden gemotiveerd door het kijken naar de Olympische spelen, in Haven-Stad wordt bewegen en sporten gemotiveerd, hiervoor wordt geïnvesteerd in parken, speeltuinen en sportvoorzieningen. Er wordt ruimte gemaakt voor sport, hierbij zal de focus liggen op het mogelijk maken van sporten en bewegen in de breedste zin.', '\"Haven-Stad sluit zich hiermee aan bij het programma “De Bewegende Stad”', 'nu.png'),
(20, 'mobiliteit', '6-11-2018', '“Rijkswaterstaat keurt ontwerpen voor fietsbrug over Amsterdams IJ af”', 'Rijkswaterstaat heeft de zes ontwerpen voor een fietsbrug over het Amsterdamse IJ die er tot nu toe lagen afgekeurd. Volgens een woordvoerder voldoen ze niet aan de veiligheidseisen, zo bevestigt hij dinsdag een artikel hierover in De Telegraaf. ', '6nov.jpg', 'https://www.nu.nl/binnenland/5555963/rijkswaterstaat-keurt-ontwerpen-fietsbrug-amsterdams-ij-af.html', 'Voor de Haven-Stad zijn er ook plannen om een fietsbrug te maken. Er ligt een plan voor een fietsbrug richting Vredenhof en een fietsbrug over het Zijkanaal-H. Naast de fietsbruggen worden er verschillende fietsverbindingen gecreëerd om fietsnetwerken aan te bieden aan bewoners en bezoekers. De routes worden onder anderen zo aangelegd dat ze naar recreatiegebieden lijden, het zorgt voor een goede verbinding met de omliggende buurten en het is makkelijk om in het stedelijk gebied te komen.', '\"Het zorgt voor een goede verbinding met de omliggende buurten en het is bovendien makkelijk om in het stedelijk gebied te komen.\"', 'nu.png'),
(21, 'duurzaamheid', '19-2-2018', '“ING en EIB steken 300 miljoen euro in groene scheepvaart”', 'De Europese Inversteringsbank (EIB) en ING roepen een fonds in het leven dat gaat investeren in duurzame scheepvaart. Ze steken daar ieder 150 miljoen euro in. Het geld is gaat naar de bouw van nieuwe, schonere schepen en het verbouwen van bestaande. “Het zal geen geheim zijn dat de scheepvaartsector een belangrijke bijdrage levert aan de CO2-uitstoot. Dit soort financiering worden gezien als een stimulans voor reders om te overwegen zaken anders aan te pakken”, zegt EIB-president Werner Hoyer', '19feb.jpg', 'https://www.nu.nl/ondernemen/5141249/ing-en-eib-steken-300-miljoen-euro-in-groene-scheepvaart.html', 'De scheepvaart in Haven-Stad leidt tot veel uitstoot, Haven-Stad ligt hierbij op de voorgrond, maar er zijn gelukkig veel mogelijkheden om de scheepvaart te beperken. Dat kan bijvoorbeeld gedaan worden door binnenvaartschepen en laad-/losactiviteiten op afstand van woonbebouwing te laten aanleggen en te voorzien van walstroom.', '\"Er zijn gelukkig veel mogelijkheden om de scheepvaart te beperken in Haven-Stad\"', 'nu.png'),
(22, 'leven', '2-11-2018', '“Spoorwegen openen ‘eerste’ watertappunt op station Alkmaar”', 'Op 31 oktober is het NS-watertappunt op station Alkmaar feestelijk geopend. Directeuren van NS en drinkwaterbedrijf PWN tapten water voor wethouder Marcel van Zon van de gemeente Alkmaar en voor de eerste reizigers. De Nederlandse Spoorwegen hebben de ambitie om voor het einde van 2019 op 200 stations in Nederland watertappunten aan te leggen. Het is de eerste stap op weg naar gratis drinkwater voor iedereen, de NS beschouwd het als een extra service voor de reiziger. ', '2nov.jpg', 'https://www.waterforum.net/spoorwegen-openen-eerste-watertappunt-op-station-alkmaar/', 'NS geeft het goede voorbeeld met haar watertappunten. In de toekomst moet Haven-Stad ook gaan beschikken over genoeg tappunten. Naast dat het goed is voor het tegengaan van plastic flesjes is het ook goed als er sprake is van hittestress in het gebied.', ' \"In de toekomst moet Haven-Stad ook gaan beschikken over genoeg tappunten.\"', 'waterforum.png'),
(23, 'veiligheid', '26-2-2018', '“Kabinet stelt 75 miljoen euro extra beschikbaar voor innovatie”', 'Voor innovatie komt dit jaar 75 miljoen euro beschikbaar, laat staatssecretaris Mona Keijzer weten. Het extra geld is bestemd voor de innovatiekracht van het midden- en kleinbedrijf, het bevorderen van samenwerking tussen bedrijven, kennisinstellingen en overheid en voor toegepast onderzoek. Volgens Keijzer hebben ondernemers in het midden- en kleinbedrijf “een doorslaggevende rol als het gaat om innoveren. We moeten hen blijven stimuleren om kennis vanuit publiek onderzoek te benutten”', '26feb.jpg', 'https://www.nu.nl/ondernemen/5150876/kabinet-stelt-75-miljoen-euro-extra-beschikbaar-innovatie.html', 'In Haven-Stad zal je veel midden- en kleine bedrijven vinden. Haven-Stad zit vol kansen en ontwikkelingen waar samen met bedrijven wordt gezocht naar een optimaal ontwikkelingsperspectief, voor het gebied zelf als voor de nieuwe bedrijven. In Haven-Stad zijn veel ingroeihuren voor nieuwe ondernemers in de plint van gebouwen en liggen er voor de bedrijven veel kansen om duurzaamheidsdoelen te behalen. Op deze manier kunnen midden- en kleine bedrijven gestimuleerd worden door nieuwe innovaties.', '\"In Haven-Stad zal je in de toekomst veel midden- en kleine bedrijven vinden\"', 'nu.png'),
(24, 'duurzaamheid', '2-3-2018', '“Windmolens en zonnepanelen wekken weer meer stroom op”', 'In Nederland is vorig jaar ruim 10 procent meer elektriciteit uit hernieuwbare bronnen opgewekt dan het jaar ervoor. Zowel de productie van zonne- als van windenergie nam toe, die van biomassa juist iets af. De productie van duurzame elektriciteit is de afgelopen tien jaar flink, en vrijwel in een rechte lijn gegroeid.', '2maa.jpg', 'https://www.nu.nl/economie/5156705/windmolens-en-zonnepanelen-wekken-weer-meer-stroom.html', 'In Haven-Stad worden in de toekomst veel windmolens en zonnepanelen gebruikt. In 2040 moet voor ten minste 12.000 huishoudens extra windenergie zijn en komt voor 80.000 huishoudens elektriciteit van zonnepanelen. In de agenda “duurzaamheid” van de Gemeente van Amsterdam zijn gebieden aangewezen waar de gemeente samen met ontwikkelaars, woningcorporaties en partijen als Alliander, AEB, Amsterdam en Waternet, alles uit de kast haalt op het gebied van duurzaamheid. ', '\"In Haven-Stad worden in de toekomst veel windmolens en zonnepanelen gebruikt\"', 'nu.png'),
(25, 'wonen', '30-10-2018', '“Huren in Rotterdam en Eindhoven stijgen harder dan die in Amsterdam“', 'De huurprijzen in de vrije sector in Rotterdam en Eindhoven gaan de laatste twee kwartalen harder omhoog dan die in Amsterdam, Utrecht en Den Haag. Volgens dinsdag gepubliceerde cijfers van verhuurplatform Pararius liet Rotterdam van de vijf grote steden afgelopen kwartaal de sterkste groei zien. Het ging in de Havenstad om een toename van 14,3 procent op jaarbasis. Eindhoven kwam daar vlak achteraan, met een huurprijsstijging van 12,1 procent. ', '30okt.jpg', 'https://www.nu.nl/geldzaken/5541770/huren-in-rotterdam-en-eindhoven-stijgen-harder-dan-in-amsterdam.html', 'De wijken in de Haven-Stad zullen erg gemengd zijn. Er liggen plannen klaar voor sociale huurwoningen, woningen voor ouderen en woningen voor gehandicapten. Het is in de Haven-Stad erg belangrijk dat er een menging is op sociaal-economisch gebied.', '\"De wijken in de Haven-Stad zullen erg gemengd zijn.\"', 'nu.png'),
(26, 'mobiliteit', '13-3-2018', '“Waymo wil diverse modellen zelfrijdende auto’s voor specifieke ritjes inzetten”', 'Waymo, een zusterbedrijf van Google dat zich richt op de ontwikkeling van zelfrijdende auto’s gaat in de toekomst verschillende modellen autonome wagens uitbrengen die zijn toegespitst op specifieke soorten ritjes. Wanneer de verschillende soorten auto’s precies op de markt komen en in welke gebieden, wilde Krafick niet zeggen. Wel zei hij dat de situatie met unieke modellen voor specifieke ritten zeker in 2028 gerealiseerd moet zijn.', '13maa.jpg', 'https://www.nu.nl/gadgets/5175383/waymo-wil-diverse-modellen-zelfrijdende-autos-specifieke-ritjes-inzetten.html', 'Zelfrijdende auto’s, dit komt voor in het toekomstbeeld van Haven-Stad. De zelfrijdende auto’s zijn in opkomst, dit gaat in Haven-Stad zorgen voor meer capaciteit op de wegen. De capaciteit op de wegen in Haven-Stad wordt vergroot doordat voertuigen dichter bij elkaar kunnen rijden. ', '\"Zelfrijdende auto’s, dit komt voor in het toekomstbeeld van Haven-Stad\"', 'nu.png'),
(27, 'mobiliteit', '4-4-2018', '“Snelle treindienst tussen Londen en Amsterdam van start”', 'Vanaf woensdag rijden er dagelijks snelle treinen vanuit Londen naar Amsterdam. Rond half 8 woensdagochtend arriveerde de eerste (betalende) passagiers met de Eurostar-trein vanuit de Britse hoofdstad. Totale reisduur: 3 uur 41 minuten. Voorheen was dat bijna een uur langer, omdat reizigers in Brussel moesten overstappen, dit is nu verleden tijd.', '4apr.jpg', 'https://www.ad.nl/amsterdam/snelle-treindienst-tussen-londen-en-amsterdam-van-start~a1d1f902/', 'Vervoer in Haven-Stad is erg belangrijk, als er geen goede mobiliteit is wordt de bouw van Haven-Stad direct verkleind. In Haven-Stad wordt een multimodaal knooppunt ontwikkeld door de trein, tram, metro en autowegen in Haven-Stad. De verkeersinfrastructuur wordt verbonden met de stad en de regio, daardoor is het erg geschikt voor alle toekomstige kantoren in Haven-Stad.', '\"De verkeersinfrastructuur wordt verbonden met de stad en de regio\"', 'ad.png'),
(28, 'mobiliteit', '5-4-2018', '“Amsterdamse Noord-Zuidlijn gaat definitief op 22 juli rijden”', 'De Amsterdamse Noord-Zuidlijn gaat definitief op 22 juli rijden. De metro, die Amsterdam-Noord met de Zuidas verbindt, zal wel met een aangepaste dienstregeling gaan rijden. Volgens deskundigen moet er nog veel gebeuren voordat de nieuwe metrolijn Amsterdam-Noord met de Zuidas kan verbinden. Zo zouden de betrokken organisaties onvoldoende op elkaar zijn afgestemd. De deskundigen hadden de gemeente geadviseerd om de openingsdatum van 22 juli nog niet vast te leggen.', '5apr.jpg', 'https://www.nu.nl/binnenland/5208617/amsterdamse-noord-zuidlijn-gaat-definitief-22-juli-rijden.html', 'In Haven-Stad staat een nieuwe metro op de planning voor 2040, dit zal gaan zorgen voor een goede uitwisseling tussen Amsterdam en de regio hier om heen. De nieuwe metro wordt verbonden met de halte van de Noord-Zuidlijn en zal zorgen voor meer mobiliteit. Het is belangrijk dat de kostbare metrolijn zo snel mogelijk gaat beginnen, het aanleggen van een nieuwe metrolijn neemt al gauw 15 tot 20 jaar in beslag. In 2040 zal Haven-Stad door het nieuwe metronetwerk groeien als het gaat om mobiliteit.', '\"In 2040 zal Haven-Stad door het nieuwe metronetwerk groeien als het gaat om mobiliteit\"', 'nu.png'),
(29, 'leven', '24-10-2018', '“Amsterdamse kantoorpanden zien grootste prijsstijging ter wereld”', 'De waarde van kantoorpanden in Amsterdam steeg dit jaar harder dan die van panden in buitenlandse grote steden. In het derde kwartaal bedroeg de waardestijging in Amsterdam maar liefst 27,4 procent. Een groeiende vraag van beleggers en huurders en relatief weinig nieuwbouw zijn oorzaken van de waardeverhoging in Amsterdam. \r\n', '24okt.jpg', 'https://www.nu.nl/ondernemen/5530748/amsterdamse-kantoorpanden-zien-grootste-prijsstijging-wereld.html', 'De Haven-Stad wordt een hoogstedelijk gebied met genoeg ruimte voor bedrijven. Door de opkomst van de kennis- en innovatie economie komt er een grotere vraag naar gemengde steden zoals Haven-Stad. Er zullen in de Haven-Stad verschillende opties voor kleinschalige bedrijfsruimtes en werkruimtes voor ambachten mogelijk zijn.\r\n', '\"De Haven-Stad wordt een hoogstedelijk gebied met genoeg ruimte voor bedrijven.\"', 'nu.png'),
(30, 'wonen', '22-10-2018', '“Opnieuw forse prijsstijging koopwoningen”', 'Bestaande koopwoningen zijn in september met 9,3 procent in prijs gestegen vergeleken met een jaar eerder. In augustus van dit jaar stegen de woningprijzen met hetzelfde percentage. Sinds juni 2013 is er sprake van een stijgende trend in de prijzen van bestaande koopwoningen. Sinds mei 2018 staat de prijsindex hoger dan het recordniveau van augustus 2008 en sindsdien worden nieuwe records geboekt.\r\n', '22okt.jpg', 'https://www.nu.nl/wonen/5526728/opnieuw-forse-prijsstijging-koopwoningen.html', 'Haven-Stad word een inclusieve stad met veel gezichten; studenten en expats, starters en senioren, alleenstaanden en gezinnen. Er is plek voor iedereen. In Haven-Stad zetten we de Amsterdamse traditie voort om te streven naar wijken met een gemengde bevolkingssamenstelling met voldoende aandacht voor ruimte voor kwetsbare groepen.\r\n\r\n', '\"Haven-Stad word een inclusieve stad met veel gezichten; studenten en expats, starters en senioren, alleenstaanden en gezinnen.\"', 'nu.png'),
(31, 'duurzaamheid', '19-10-2018', '“Haven Amsterdam wil met Tata Steel waterstoffabriek bouwen”', 'Havenbedrijf Amsterdam, Nouryon (voorheen AkzoNobel Specialty Chemicals) en staalbedrijf Tata Steel bundelen de krachten om een waterstoffabriek in het Noordzeekanaalgebeid van de grond te krijgen. Het initiatief is onderdeel van de energietransitie in het havengebied, waarbij bijvoorbeeld door waterstof te combineren met emissies uit staalproductie nieuwe grondstoffen kunnen worden gemaakt. De fabriek maakt een CO2-besparing van circa 350.000 ton per jaar mogelijk. ', '19okt.jpg', 'https://www.nieuwsbladtransport.nl/havens/2018/10/19/haven-amsterdam-wil-met-tata-steel-waterstoffabriek-bouwen/', 'Duurzame energie, energieneutraal bouwen en aardgasloos ontwikkelen, dit zijn belangrijke onderdelen in de duurzame ontwikkeling van Haven-Stad. Door energiezuinige gebouwen te bouwen in Haven-Stad met de warmte- en koudevoorzieningen nemen we grote stappen in het verminderen van de CO2-uitstoot. Haven-Stad slaagt er helaas niet om deze maatregelen met 75% CO2-redutie in 2040 te behalen. Een waterstoffabriek in het havengebied zal helpen naar het doel om CO2-uitstoot te verminderen. \r\n', '\"Een waterstoffabriek in het havengebied zal helpen naar het doel om CO2-uitstoot te verminderen\"', 'nieuwsbaldtransport.png'),
(32, 'duurzaamheid', '18-10-2018', '“Subsidie voor overstappende snorfietsbezitters naar duurzaam alternatief”', 'Snorfietsbezitters kunnen binnenkort subsidie aanvragen wanneer zij naar een schoner vervoersmiddel overstappen. Het college hoopt dat dit bijdraagt aan een betere luchtkwaliteit in de stad. Met de subsidieregeling wil Amsterdam snorfietsbezitters stimuleren over te stappen op schonere alternatieven, zoals de fiets of een elektrisch voertuig. De regeling is in lijn met het voornemen voor een uitstootvrije stad in 2015, meldt de gemeente. ', '18okt.jpg', 'https://www.nu.nl/amsterdam/5521592/subsidie-overstappende-snorfietsbezitters-duurzaam-alternatief.html', 'De inzet van OV- en fietsgebruik in Havenstad wordt belangrijk om het autogebruik te verminderen om zo de luchtkwaliteit zo schoon mogelijk te houden. Haven-Stad wordt onderdeel van de milieuzone, dit betekend dat oude en vervuilende voertuigen, waaronder snorfietsen, hier niet mogen rijden. Haven-Stad krijgt hiermee de kwaliteit die binnen de ring van Amsterdam geldt. \r\n', '\"De inzet van OV- en fietsgebruik in Havenstad wordt belangrijk om het autogebruik te verminderen om zo de luchtkwaliteit zo schoon mogelijk te houden.\"', 'nu.png'),
(33, 'duurzaamheid', '18-9-2018', '“Nederland krijgt luierrecyclingfabriek”', 'We scheiden groenafval, restafval en plastic. Maar geen luiers, terwijl ook die voor een erg grote afvalberg zorgen. Kinderen en ouderen produceren jaarlijks namelijk zo’n 1 miljard luiers en dat zal in de toekomst alleen maar meer worden. Een afvalverwerker in Nijmegen bedacht een oplossing: vandaag is daar de bouw van een heuse luierrecylingfabriek gestart. De luierrecyclingfabriek maakt van de oude luiers vier producten: groen gas, plastic, kunstmest en biomassa.\r\n', '18sep.jpg', 'https://www.metronieuws.nl/in-het-nieuws/2018/09/nederland-krijgt-luierrecyclingfabriek', 'In Haven-Stad willen we graag afval gaan hergebruiken tot grondstof. De gemeente heeft hiervoor doelen opgesteld om efficiënt om te gaan met grondstoffen. In de toekomst willen we zoveel mogelijk afval hergebruiken van materialen en grondstoffen in het afval. De doelstelling in Haven-Stad is 65% scheiding van (huishoudelijk) afval in 2020.\r\n', '\"In Haven-Stad willen we graag afval gaan hergebruiken tot grondstof.\"', 'metro.png'),
(34, 'leven', '14-9-2018', '“Stadsdeel wil overlast Westerpark beteugelen”', 'De overlast voor omwonenden door evenementen in het Westerpark moet omlaag. Dat schrijft het dagelijks bestuur van West in de notitie Westerpark in Balans die vrijdag verschijnt. De populariteit van het Westerpark is de afgelopen jaren enorm toegenomen.  Het intensieve gebruik gaat regelmatig ten koste van de leefbaarheid en de kwaliteit van het park en zijn omgeving. “Met de bewoners zijn wij van mening dat de overlast te groot wordt,” zegt dagelijks bestuurder Melanie van der Horst.', '14sep.jpg', 'https://www.parool.nl/amsterdam/stadsdeel-wil-overlast-westerpark-beteugelen~a4604464/', 'Het Westerpark in Haven-Stad moet op middellange en lange termijn de groengebieden klaar hebben door het gevolg van de groei in Amsterdam. In de toekomst wordt het Westerpark een plek met veel ruimte en rust, maar ook voor reuring en vermaak. In het Westerpark wordt er rekening gehouden met de bezoekers, zo ook op het gebied van rust.\r\n', '\"In het Westerpark wordt er rekening gehouden met de bezoekers.\"', 'parool.png'),
(35, 'leven', '20-4-2018', '“Aantal rokers in Nederland daalt steeds verder”', 'Het aantal rokers is verder gedaald. Rookte in 2016 nog 24,1% (waarvan 18,6% dagelijks), vorig jaar is dat gedaald naar 23,1% (17,2% dagelijks). dit blijkt uit cijfers van de Gezondheidsenquête/leefstijlmonitor CBS, samen met het Trimbos-instituut en het RIVM. Het succes is onder andere toe te schrijven aan verslavingsarts Robert van de Graaf. Hij maakt samen met de plaatselijke huisarts Ureterp tot het eerste rookvrije dorp van Nederland. ', '20apr.jpg', 'https://www.hartvannederland.nl/nieuws/2018/aantal-rokers-in-nederland-daalt-steeds-verder/', 'Haven-Stad wordt in de toekomst een stad waar gezond en bewust geleefd wordt. De gezondheid in Haven-Stad wordt beter door gezond gedrag, hierbij gaat het ook over roken. Er zullen in Haven-Stad rookvrije speelvoorzieningen en rookvrije sportvoorzieningen geopend worden, dit is belangrijk voor zowel de kinderen als voor de andere inwoners van Haven-Stad.', '\"Haven-Stad wordt in de toekomst een stad waar gezond en bewust geleefd wordt\"', 'hartvannederland.png'),
(36, 'duurzaamheid', '3-5-2018', '“Wereldprimeur voor Amsterdamse Haven”', 'Bin2Barrel en Port of Amsterdam zijn begonnen met de bouw van een nieuwe fabriek in de Amsterdamse Haven. De fabriek gaat niet-recyclebaar plastic omzetten in brandstof voor de transportsector. Met deze innovatieve technologie heeft de haven een wereldprimeur. Op jaarlijkse basis bespaart de fabriek hiermee 57.000 ton CO2-uitstoot. Het is het eerste project van Bin2Barrel, een Nederlandse onderneming die zich toelegt op het ontwikkelen van ‘Plastic to Fuel’ projecten.', '3mei.jpg', 'https://www.portofamsterdam.com/nl/nieuwsbericht/wereldprimeur-voor-amsterdamse-haven', 'In Haven-Stad wordt afval gescheiden. Door het scheiden van afval zorgen de huishoudens en bedrijven samen voor recycling. Grondstoffen worden hergebruikt voor bijvoorbeeld de scheepvaart of de bouwsector, er ontstaat een circulaire economie. De ambitie om op het gebied van recycling te ontwikkelen staat op de planning voor 2040.', '\"Door het scheiden van afval zorgen de huishoudens en bedrijven samen voor recycling\"', 'portofamsterdam.png'),
(37, 'wonen', '20-3-2018', '“Pontsteiger is bijna af! 1 mei overhandiging eerste sleutels”', 'We weten steeds meer over wanneer de eerste huurappartementen in Pontsteiger klaar zijn. Het gebouw is steeds verder klaar. In fases gaan we de woningen opleveren aan de eerste huurders. 1 mei kunnen we de eerste sleutels in de onderbouw overhandigen. Vervolgens zal in fases het gebouw voltooid worden. De huurappartementen in de twee torens zijn als laatste aan de beurt, waarna de koopappartementen volgen in de ‘brug’.', '20maa.jpg', 'http://pontsteiger.nl/#home-pontsteiger https://hureninpontsteiger.nl/nieuws/pontsteiger-is-bijna-af-begin-mei-overhandiging-eerste-sleutels/', 'Pontsteiger is het unicum van Haven-Stad. Het gebouw is een spraakmakend ontwerp aan het water en één van de nieuwste woningen dat op de planning stond van Haven-Stad. Pontsteiger is in fase 1a van Haven-Stad gebouwd, in fase 1a van Haven-Stad moeten er 14.800 woningen gebouwd zijn en 20.500 arbeidsplaatsen beschikbaar zijn. Pontsteiger is zeker één van de eyecatchers van Haven-Stad en dat zal het in 2040 nog steeds zijn!', '\"Pontsteiger is het unicum van Haven-Stad\"', 'pontsteiger.png'),
(38, 'duurzaamheid', '2-5-2018', '“Jaarlijks sterven acht miljoen mensen door gevolgen luchtvervuiling”', 'Jaarlijks sterven acht miljoen mensen wereldwijd door luchtverontreiniging. Dat schat de Wereldgezondheidsorganisatie (WHO) in een rapport dat woensdag wordt gepresenteerd. Uit gegevens van de WHO blijkt dat 80 procent van de mensen in een stad wonen vervuilde lucht inademen. De VN-organisatie houdt een database bij over de luchtkwaliteit van 4.300 steden in 108 landen.', '2mei.jpg', 'https://www.nu.nl/gezondheid/5247758/jaarlijks-sterven-acht-miljoen-mensen-gevolgen-luchtvervuiling.html', 'In 2040 wil Haven-Stad zich bezig gaan houden met luchtverontreiniging. De eerste stap is het verminderen van het autoverkeer, de kleine roetdeeltjes (fijnstof) zijn de belangrijkste oorzaak van gezondheidsschade. Daarnaast zal in Haven-Stad de bestaande milieuzones uitgebreid worden, wordt de uitstoot van scheepvaart verminderd en zal gezond gedrag gestimuleerd worden. In 2025 moet er 30% minder uitstoot zijn van roet en 35% minder uitstoot zijn van stikstofdioxide door slim en schoon vervoer. ', '\"In 2040 wil Haven-Stad zich bezig gaan houden met luchtverontreiniging\"', 'nu.png'),
(39, 'leven', '8-5-2018', '“Meer werk en meer groei, maar de inkomsten blijven weer achter”', 'De groei van het netto besteedbaar inkomen is ook vorig jaar achtergebleven bij die van de werkgelegenheid en de economie als geheel. Het netto reëel besteedbaar inkomen groeide vorig jaar met 1,5%. Dit is het bedrag dat overblijft om uit te geven, na aftrek van alle belastingen en premies en gecorrigeerd voor inflatie. In 2017 waren volgens het CBS meer mensen aan het werk dan ooit. Het aantal werklozen daalde met een recordaantal van 100.000 en ook het aantal vacatures is nog nooit zo geweest.', '8mei.jpg', 'https://www.nu.nl/geldzaken/5255198/meer-werk-en-meer-groei-maar-inkomens-blijven-weer-achter.html', 'Haven-Stad wordt een gemengd, hoogstedelijk gebied met voldoende ruimte voor bedrijven. De opkomst van de kennis- en innovatie-economie zorgt voor veel vraag naar gemengde stedelijke milieus zoals Haven-Stad. Hier gaat het over een mix van kleinschalige bedrijfsruimte, dit kan ingevuld worden met kantoorachtige concepten uit de creatieve kennis- en innovatie-economie, maar ook met werkruimtes voor ambachten, kleinschalige productieve diensten, stadsverzorgende diensten en technische incubators. ', '\"Haven-Stad maakt plek voor ondernemers\"', 'nu.png'),
(40, 'wonen', '6-6-2018', '“Wonen in hoge dichtheden biedt kansen”', 'Onderzoek wijst uit dat wonen in hoge dichtheden kansen biedt voor Nederland. De studie van gebieds- en vastgoedontwikkelaar AM concludeert dat wonen in hoge dichtheid kansen biedt, mits de omgeving voldoet aan een hoge mate van kwalitatief groene omgeving, voorzieningen, ruimte voor ontmoeting en goed openbaar vervoer.', '6jun.jpg', 'https://www.vastgoedmarkt.nl/projectontwikkeling/nieuws/2018/06/wonen-hoge-dichtheden-biedt-kansen-101133660?vakmedianet-approve-cookies=1&_ga=2.60502701.1097831277.1545136206-276670879.1538389266', 'Haven-Stad, het gebied dat gaat bestaan uit hoge dichtheden. Bewoners van Haven-Stad kunnen een levendige wijk verwachten met een mix aan functies, activiteiten en hoogstedelijke woningtypen. In Haven-Stad wordt een woonmilieu gecreëerd met hoge dichtheden waarbij wordt aangesloten op bijzondere karakteristieken van het gebied, zoals de robuuste havenbekkens van het cornelis Douwesterrein, de groene ambiance van het Westerpark of het bestaande hoogbouwmilieu van Sloterdijk-Centrum.', '\"Haven-Stad, het gebied dat gaat bestaan uit hoge dichtdeden\"', 'vastgoedmarkt.png'),
(41, 'mobiliteit', '18-6-2018', '“Houthaven viert feestelijke opening van de Pontsteigergarage”', 'Afgelopen vrijdag is het project Kistdamgarage officieel geopend die vanaf nu te naam staat als ‘Pontsteigergarage’. In opdracht van de gemeente Amsterdam veranderde Bouwcombinatie Dura Vermeer - De Nijs de Pontsteiger de afgelopen 2 jaar onherkenbaar. Direct onder de Pontsteiger ligt een moderne parkeergarage met 275 parkeerplekken exclusief voor vergunninghouders uit de Spaarndammerbuurt en Zeeheldenbuurt. ', '18jun.jpg', 'https://www.duravermeer.nl/nieuws/houthaven-viert-feestelijke-opening-van-de-pontsteigergarage', 'Vervoeren over het water, iets waar Haven-Stad nu al hard voor aan werk is. Water kan in Haven-Stad gebruikt worden om de bereikbaarheid van het gebied groter te maken. In Amsterdam zijn ze bezig om de bereikbaarheid beter te maken door privéboten, watertaxi’s en OV-ponten. Het gebruik van vervoer op het water voorkomt het aanleggen van dure bruggen. Haven-Stad gaat de aankomende jaren bezig met het aanleggen van pontverbindingen tussen het Noordelijke en Zuidelijke deel van Haven-Stad.', '\"Vervoeren over het water, iets waar Haven-Stad nu al hard voor aan werk is\"', 'duravermeer.png'),
(42, 'leven', '21-6-2018', '“Het nut van een (lange) wandeling”', 'Uit onderzoekscijfers van het Centraal Bureau van Statistiek (CBS) blijkt dat het aantal te voet afgelegde kilometers onder Nederlanders sinds 2005 met 11 procent is toegenomen. “Ons cognitieve brein wordt gedurende de hele dag belast: momenten van rust zijn er bijna niet, om dat ons werk en onze smartphone veel aandacht opeisen. Met wandelen laat je die druk letterlijk van je af vallen. Daardoor gaan we weer mijmeren en creatief zijn.”', '21jun.jpg', 'https://www.nu.nl/uit/5324042/nut-van-lange-wandeling.html ', 'In Haven-Stad willen de toekomstige bewoners graag recreatieve voorzieningen, maar liefst 80% van de mensen zou gebruik willen maken van een wandelpromenade als deze langs een oever wordt aangelegd. De voorzieningen op dit moment worden weinig gebruikt door omwonenden, tijd voor verandering!', '\"In Haven-Stad willen de toekomstige bewoners graag recreatieve voorzieningen\"', 'nu.png'),
(43, 'duurzaamheid', '25-6-2018', '“Van Veldhoven trekt 10 miljoen extra uit voor voor luchtkwaliteit binnensteden”', 'De luchtkwaliteit in alle Nederlandse binnensteden zal naar verwachting eind dit jaar voldoen aan de Europese waarden. Dat blijkt uit nieuwe prognoses, meldt staatssecretaris Steintje van Veldhoven aan de Tweede Kamer.\r\nOm dit doel te bereiken, trekt de bewindsvrouw 10 miljoen extra uit voor maatregelen die de luchtkwaliteit in Amsterdam, Arnhem, Eindhoven, Rotterdam en Utrecht moeten verbeteren. Een deel van het geld gaat bijvoorbeeld naar subsidies voor elektrische taxi’s in de hoofdstad. \r\n', '25jun.jpg', 'https://www.nu.nl/binnenland/5329244/van-veldhoven-trekt-10-miljoen-extra-luchtkwaliteit-binnensteden.html', 'In Haven-Stad vinden we het erg belangrijk dat er een gezonde leefomgevingskwaliteit is voor de bewoners en werkende mensen. Tijdens de transformatie van Haven-Stad worden er bijvoorbeeld rekening gehouden met het verbeteren van de luchtkwaliteit. Binnen Haven-Stad vinden we duidelijke keuzes belangrijk, vooral als het gaat om de relatief hoge milieubelasting door het overgangsgebied van haven en stad.', '\"Binnen Haven-Stad vinden we duidelijke keuzes belangrijk\"', 'nu.png'),
(44, 'leven', '27-6-2018', '“Femke Halsema nieuwe burgemeester Amsterdam”', 'Femke Halsema is woensdag voorgedragen als nieuwe burgemeester van Amsterdam. In een geheime stemming koos een meerderheid van de gemeenteraad voor de oud-leider van GroenLinks. De Amsterdamse raad had een duidelijke voorkeur uitgesproken voor een vrouw. Gezien de linkse meerderheid in de raad lag het voor de hand dat de nieuwe burgemeester afkomstig zou zijn van een GroenLinks, D66 of de PvdA.', '27jun.jpg', 'https://www.nrc.nl/nieuws/2018/06/27/femke-halsema-nieuwe-burgemeester-amsterdam-a1608165', 'De Gemeente van Amsterdam is erg druk met de bouw van Haven-Stad. Vijf jaar geleden stelde de gemeenteraad van Amsterdam, aansluitend op de Structuurvisie 2040, de Transformatiestrategie Haven-Stad vast. Vandaag de dag en in de toekomst van Haven-Stad zal de Gemeente van Amsterdam een grote rol spelen. Zo zal Femke Halsema hier ook in meespelen en beslissingen nemen binnen het project.', '\"De Gemeente van Amsterdam is erg druk met de bouw van Haven-Stad\"', 'nrc.png'),
(45, 'duurzaamheid', '29-6-2018', '“Milieuzones: twee varianten voor diesels”', 'Bezitters van een personenauto die rijdt op diesel, kunnen op twee manieren te maken krijgen met een milieuzone in Nederland. Gemeenten die een milieuzone zouden willen invoeren, krijgen de mogelijkheid om auto’s ouder dan 15 jaar of ouder dan 20 jaar in hun zone te weigeren.', '29jun.jpg', 'https://www.rijksoverheid.nl/actueel/nieuws/2018/06/29/milieuzones-twee-varianten-voor-diesels', 'In 2014 werd in Amsterdam al een milieuzone ingezet voor het vrachtverkeer, in 2015 werd er onderzoek gedaan naar milieuzones voor scooters in de stad en in 2017 werden er milieuzones ingevoerd voor bestelvervoer. In de toekomst worden de milieuzones voor taxi’s, touringscar’s en vrachtverkeer aangescherpt. De milieuzones zorgen voor een schonere lucht in Haven-Stad. ', '\"De milieuzones zorgen voor een schonere lucht in Haven-Stad\"', 'rijksoverheid.png'),
(46, 'duurzaamheid', '30-6-2018', '“Gemeenten zamelen meer afval gescheiden in”', 'In 2017 werd 57% van het huishoudelijk afval gescheiden ingezameld, tegen 49% in 2007. Huishoudens leverden vooral meer groente-, fruit- en tuinafval (gft) en verpakkingen (pmd) apart in. DAt meldt het CBS op basis van nieuwe cijfers. Steeds meer gemeenten laten hun inwoners niet al hun afval gescheiden inleveren, maar laten het restafval nascheiden. Recyclebare stoffen worden dan achteraf uit het restafval gehaald en dus niet verbrand.', '30jun.jpg', 'https://www.cbs.nl/nl-nl/nieuws/2018/26/gemeenten-zamelen-meer-afval-gescheiden-in', 'In Haven-Stad is het scheiden van afval erg belangrijk, in de toekomst zal dit van 19% naar 65% gescheiden huishoudelijk afval moeten gaan. Het afval in Haven-Stad is grondstof. De materialen worden opnieuw gebruikt voor nieuwe productie, consumptie en distributie.', '\"Het afval in Haven-Stad is grondstof\"', 'cbs.png'),
(47, 'leven', '1-7-2018', '“Hitteplan nog in de koelkast”', 'Het is behoorlijk warm, maar het welbekende “hitteplan” komt er voorlopig nog niet. Dat bevestigt het Rijksinstituut voor Volksgezondheid en Milieu. Reden: het is nog niet heet genoeg. Bij een door het KNMI verwachte hoge temperatuur voor vier dagen of meer, zet het RIVM het Nationale Hitteplan in werking. Er wordt dan extra geadviseerd om goed op de zwakkere groepen in de samenleving te letten en het RIVM ondersteunt de GGD met het beantwoorden van vragen. ', '1jul.jpg', 'https://www.telegraaf.nl/nieuws/2241940/hitteplan-nog-in-de-koelkast', 'In Haven-Stad wordt niet specifiek een hitteplan opgesteld, wel wordt er over hittestress gepraat. Hittestress wordt in de toekomst van Haven-Stad tegengegaan door veel groen en water en zo min mogelijk stenige gladde oppervlakken in het gebied. In Haven-Stad houden we rekening met hittestress en zonbescherming.', '\"In Haven-Stad houden we rekening met hittestress en zinbescherming\"', 'telegraaf.png'),
(48, 'leven', '4-7-2018', '“Groot alarm om obesitas”', 'Het aantal volwassen Nederlanders dat lijdt aan morbide obesitas, een ernstigste vorm van zwaarlijvigheid, is opgelopen tot boven de 100.000. In totaal heeft 14% enige vorm van obesitas. Dat is ruim 2,5 keer meer dan begin jaren tachtig, blijkt uit onderzoek van het CBS en het RIVM.', '4jul.jpg', 'https://www.telegraaf.nl/nieuws/2255424/groot-alarm-om-obesitas', 'Een gezonde leefomgeving is een belangrijke bouwsteen in Haven-Stad. Met de ontwikkeling van Haven-Stad is een gezonde leefomgeving één van de belangrijkste punten, hierin speelt voedsel ook een grote rol. Tijdens de transformatie wordt er rekening gehouden met gezond gedrag door voldoende beweging, rookvrije- speel en sportvoorzieningen en gezonde voeding (snack-barvrije zonde rondom scholen).', '\"Een gezonde leefomgeving is een belangrijke bouwsteen in Haven-Stad\"', 'telegraaf.png'),
(49, 'duurzaamheid', '5-7-2018', '“Shell zoekt naar kansen met opwekken energie”', 'Shell zoekt naar kansen met het opwekken van energie. De beste mogelijkheden liggen waarschijnlijk in de offhorse windsector of bijvoorbeeld bij zonne-energie. Dit heeft Sinead Lynch, het hoofd van Shell UK, gezegd op een evenement in Londen.', '5jul.jpg', 'https://www.telegraaf.nl/financieel/2264933/shell-zoekt-naar-kansen-met-opwekken-energie', 'In Haven-Stad kan lokaal duurzame elektriciteit opgewekt worden, maar dit zal niet genoeg zijn voor de energievraag in het gebied. De ruimte om duurzame elektriciteit op te wekken in Haven-Stad is beperkt door de hoge dichtheid. In de toekomst willen we in Haven-Stad ten minste 12.000 huishoudens voorzien door windenergie en zonne-energie.', '\"In Haven-Stad kan lokaal duurzame elektriciteit opgewekt worden\"', 'telegraaf.png'),
(50, 'leven', '6-7-2018', '“BMI is goede indicator voor overgewicht, maar zegt niet alles”', 'Het aantal mensen met overgewicht en obesitas is flink gestegen sinds de jaren tachtig, bleek eerder deze week uit cijfers van het Centraal Bureau voor de Statistiek (CBS) en het RIVM. De cijfers werden berekend op basis van het BMI. Een diëtiste vertelt “Overgewicht over het algemeen is niet gezond. Ik trek weleens de vergelijking met roken: natuurlijk mag je er zijn met je overgewicht, net zoals rokers er mogen zijn. maar we hoeve nog niet te beweren dat roken gezond is.”', '6jul.jpg', 'https://www.nu.nl/gezondheid/5350049/bmi-goede-indicator-overgewicht-maar-zegt-niet-alles.html', 'Een bewegende stad, dat moet Haven-Stad gaan worden. Het bevorderen van bewegen draagt bij aan de gezonde leefomgevingskwaliteit in het gebied en is een prioriteit in de transformatie van Haven-Stad. Het doel van het programma “De Bewegende Stad” is om de stad zo in te richten dat hij bezoekers, bewoners en werkenden uit te nodigen tot bewegen, ofterwijl gezonder leven met minder overgewicht.', '\"Een bewegende stad, dat moet Haven-Stad gaan worden\"', 'nu.png'),
(51, 'wonen', '17-7-2018', '“Noord-Holland bouwt 40.000 huizen bij voor Amsterdammers”', 'Duizenden Amsterdammers verlaten de stad om elder in Noord-Holland goedkoper en groter te wonen. Ze drukken lokale woningzoekers uit de markt. Daarom komen er 40.000 huizen bij. De stijgende huizenprijzen vormen een olievlek die zich vanuit Amsterdam over de regio en heel de provincie verspreid. Amsterdammers kunnen geen nieuwe woning in de stad meer betalen en kiezen ervoor om elders in Noord-Holland te gaan wonen. “Wij merken dat er veel vraag is naar binnenstedelijke woningen.” ', '17jul.jpg', 'https://www.parool.nl/amsterdam/noord-holland-bouwt-40-000-huizen-bij-voor-amsterdammers~a4601567/', 'Haven-Stad wil op dit moment 40.000 tot 70.000 woningen gaan bouwen in de toekomst. Daarnaast komen er nog 45.000 tot 58.000 arbeidsplaatsen bij. Haven-Stad wordt een gebied met binnenstedelijke woningen met een gemiddelde oppervlakte van 80 m2. In het gebied komen er veel groene ambiances voor de bewoners van Haven-Stad, op deze manier wordt groen gecombineerd met recreatie. ', '\"Haven-Stad wordt een gebied met binnenstedelijke woningen\"', 'parool.png'),
(52, 'leven', '25-7-2018', '“Hittestress bij gemeenten: dorstige ratten en losse tegels”', 'De aanhoudende hitte zorgt in steeds meer plaatsen voor problemen. Gemeenten waarschuwen voor smeltend asfalt, loszittende tegels en dichte bruggen. Maar ook voor dorstige ratten: “Een emmer water in de straatkolk is het enige wat helpt.”', '25jul.jpg', 'https://www.ad.nl/binnenland/hittestress-bij-gemeenten-dorstige-ratten-en-losse-tegels~a8d9302c/', 'Hittestress, dit komt ook voor in het gebied van Haven-Stad. Hittestress wordt in Haven-Stad tegengegaan door veel groen en water aan te leggen en te zorgen voor weinig stenige gladde oppervlakken. Door deze investeringen wordt de hittestress en zonbescherming op een gezonde manier bevorderd in Haven-Stad. ', '\"Door investeringen wordt de hittestress en zonbescherming gezond bevorderd in Haven-Stad\"', 'ad.png'),
(53, 'leven', '1-8-2018', '“Fitbit overtreft verwachtingen”', 'Fitbit heeft een beter dan verwacht kwartaal achter de rug, ondanks dat de resultaten wel terugliepen. Dat bleek uit de tweede kwartaalcijfers van de producent van fitnesshorloges en andersoortige polsbandjes. Het aandeel ging in de handel nabeurs omhoog.', '1aug.jpg', 'https://www.telegraaf.nl/financieel/2379852/fitbit-overtreft-verwachtingen', 'Steeds meer mensen kiezen ervoor om alleen te sporten, op flexibele tijdstippen en in openbare ruimtes, hierbij kan Fitbit (vooral in de toekomst) een hulpmiddel zijn. Fitbit motiveert mensen om te gaan sporten, dit sluit aan bij project Haven-Stad. In Haven-Stad zullen geen traditionele sportparken worden aangelegd, maar het mogelijk maken van sporten en bewegen in de breedste zin van het woord. ', '\"Sporten en bewegen in de breedste zin van het woord\"', 'telegraaf.png'),
(54, 'leven', '3-8-2018', '“De ‘rookvrije straat’ verovert Nederland”', 'De eerste rookvrije straten van Nederland zijn in aantocht. Burgemeester Ahmed Aboutaleb van Rotterdam heeft een brief ontvangen van drie instellingen die vragen om een verbod op sigaretten op straat. Ook in Groningen wordt aan zo’n plan gewerkt. De Erasmus MC, het Erasmiaans Gymnasium en de Hogeschool Rotterdam doen er alles aan om het roken op het eigen grondgebied te beperken. Na de vakantie wordt de hogeschool geheel rookvrij.', '3aug.jpg', 'https://www.telegraaf.nl/nieuws/2385404/de-rookvrije-straat-verovert-nederland', 'Haven-Stad ziet een soortgelijk plan zoals in Rotterdam wel zitten. Rookvrije schoolpleinen, parken, kinderspeelplaatsen en sportvelden, hier denkt Haven-Stad in de toekomst over na. Op deze manier wordt ook de gezondheid in Haven-Stad bevorderd door gezond gedrag met rookvrije plekken.', '\"Haven-Stad ziet een soortgelijk plan zoals in Rotterdam wel zitten\"', 'telegraaf.png'),
(55, 'leven', '6-8-2018', '“Bedrijven die gezondheid stimuleren hebben meer betrokken medewerkers”', 'Het gezond houden van werknemers is een essentieel element in de bedrijfsvoering van organisaties, aangezien gezondheid bepalend is voor onder meer de efficiency, productiviteit en geluk van werknemers. Veel onderzoeken in de afgelopen jaren hebben aangetoond dat gezondheid samenhangt met ziekte en verzuim. Niet verrassend geldt dat des te ongezonder werknemers leven, des te vaker deze uitvallen. ', '6aug.jpg', 'https://www.consultancy.nl/nieuws/19194/bedrijven-die-gezondheid-stimuleren-hebben-meer-betrokken-medewerkers', 'Bedrijven in Haven-Stad worden gestimuleerd om gezondheidsmaatregelen te nemen. Bedrijven kunnen dit op veel verschillende manieren gaan doen, bijvoorbeeld door het verleiden van medewerkers om met de fiets of het openbaar vervoer te reizen. Door gezondheidsmaatregelen aan te moedigen bij werkgever, blijkt uit onderzoek dat medewerkers efficiënter, productiever en gelukkigere werknemers zijn, met minder ziekte en verzuim. ', '\"Bedrijven in Haven-Stad worden gestimuleerd om gezondheidsmaatregelen te nemen\"', 'consultancynl.png');
INSERT INTO `articles` (`id`, `category`, `date`, `title`, `text`, `textorimage`, `source`, `texthavenstad`, `titlehavenstad`, `sourcelogo`) VALUES
(56, 'leven', '12-8-2018', '“Voedingscentrum wil snackbar weren uit arme wijk”', 'Het voedingscentrum wil een verbod op nieuwe snackbars in arme wijken of in de buurt van scholen. De Nederlandse regering zou volgens het Voedingscentrum in de strijd tegen overgewicht het voorbeeld moeten volgen van Los Angeles. Daar mogen in South LA ondernemers het komende jaar geen nieuwe eettenten openen waar ongezond eten wordt verkocht. Aangezien kinderen extra gevoelig zijn voor verleidingen, zou een dergelijk verbod er zeker moeten komen in de buurt van scholen, laat het centrum weten.', '12aug.jpg', 'https://www.nu.nl/algemeen/1696205/voedingscentrum-wil-snackbar-weren-uit-arme-wijk.html', 'In Haven-Stad worden voorwaarden gemaakt om een gezonde levensstijl te stimuleren: bewegen, gezond eten, het rookvrij houden van openbare ruimtes en het tegengaan van hittestress. Eén van de maatregelen waar in de toekomst aan gedacht wordt zijn de snackbarvrije zones. De snackbarvrije zone is een gebied van 250 meter rondom scholen waar geen snackbars geopend mogen worden, hierdoor zal onder naderen het Voedingscentrum erg tevreden zijn. ', '\"In Haven-Stad worden voorwaarden gemaakt om een gezonde levensstijl te stimuleren\"', 'nu.png'),
(57, 'wonen', '17-8-2018', '“Grondexploitaties leveren gemeenten miljard winst op; maar tegen welke prijs?”', 'Nog nooit eerder leverde de verkoop van bouwrijpe grond zoveel op aan gemeenten als in 2017. Hoewel nog steeds zo’n honderd gemeenten te maken hebben met een negatief saldo, werd er over heel Nederland gezien een winst van een miljard euro geboekt.', '17aug.jpg', 'https://www.gebiedsontwikkeling.nu/artikelen/grondexploitaties-leveren-gemeenten-miljard-winst-op-maar-tegen-welke-prijs/', 'Het tempo van het realiseren van Haven-Stad is afhankelijk van het opnamevermogen van de markt. Het om de woon- en bedrijfsruimte en de hoeveelheid bouwrijpe grond die beschikbaar komt voor woon-werklocaties in het gebied. Een groot deel van de grond in Haven-Stad is van bedrijven, vaak zitten hier langdurige contracten achter, hierdoor kan de transformatie van Haven-Stad alleen plaatsvinden met medewerking van de bedrijven. ', '\"De transformatie van Haven-Stad kan alleen plaatsvinden met medewerking van de bedrijven\"', 'go.png'),
(58, 'mobiliteit', '20-8-2018', '“Strakkere regie op mobiliteit zorgt voor meer capaciteit op het spoor”', 'Er valt de nodige capaciteitswinst te halen als er een strakkere regie op mobiliteit komt. Dat kan bijvoorbeeld door het wegverkeer met een kilometerheffing te beprijzen, spits- en dalgebruik van het spoor, prijsprikkels in te voeren bij opstelterreinen en snelheden te harmoniseren bij capaciteitskrapte. Dat zegt Hand-Willem Vroon van RailGood in reactie op de waarschuwing die ProRail vorige week afgaf over het steeds drukker wordende Nederlandse spoor.', '20aug.jpg', 'https://www.spoorpro.nl/goederenvervoer/2018/08/30/strakkere-regie-op-mobiliteit-zorgt-voor-meer-capaciteit-op-het-spoor/', 'De mobiliteitsingrepen zijn belangrijk om de bereikbaarheid in Haven-Stad te garanderen tijdens de bouw. De groei van het OV- en fietsinfrastructuur zal gelijk moeten lopen met de groei van Haven-Stad, dit betekend dat in de volgende fase de benodigde infrastructuur er moet zijn. Bij een latere beschikbaarheid wordt de bouw van de woningen langzamer gedaan totdat de OV-bereikbaarheid weer op peil is om de volgende fase te starten.', '\"De mobiliteitsingrepen zijn belangrijk om de bereikbaarheid in Haven-Stad te garanderen tijdens de bouw\"', 'spoorpro.png'),
(59, 'duurzaamheid', '1-9-2018', '“Verwachte verbetering blijft uit: lucht in de stad nog net zo vies”', 'Auto’s rijden over de Stadshouderskade. De luchtkwaliteit in Nederland voldoet niet aan de Europese normen. De ongezondste plek van Amsterdam is de Stadshouderskade door de relatief hoge concentratie stikstofdioxide. De luchtkwaliteit in Amsterdam is niet verbeterd. Er werd vooruitgang verwacht, maar afgelopen jaar was de lucht op tientallen plekken in de stad net zo vies als voorheen, blijkt uit metingen van de GGD.', '1sep.jpg', 'https://www.parool.nl/amsterdam/verwachte-verbetering-blijft-uit-lucht-in-de-stad-nog-net-zo-vies~a4603807/', 'In Haven-Stad moeten keuzes gemaakt worden over de Milieuruimte. Als er langer wordt gewacht met het maken van keuzes worden de maatregelen voor de milieucontouren steeds kostbaarder, hierbij kun je denken aan het uitsluiten van bedrijven in de hogere milieucategorieën. Op deze manier worden de eerste stappen naar een gezondere luchtkwaliteit in Amsterdam gezet en zullen de milieucontouren verbeteren.  ', '\"Op deze manier worden de eerste stappen naar een gezondere luchtkwaliteit in Amsterdam gezet\"', 'parool.png'),
(60, 'duurzaamheid', '20-12-2018', '“Uitlaatgas kost samenleving duizenden euro’s”', 'Giftige uitlaatgassen van auto’s kosten de samenleving gemiddeld 4000 euro per auto. Dat heeft Milieudefensie uitgerekend aan de hand van een Engels onderzoek. Door luchtvervuiling kunnen mensen namelijk ziek worden of vroegtijdig overlijden, aldus de organisatie. Dit leidt tot zorgkosten en verlies van gezonde levensjaren.', '20dec.jpg', 'https://www.telegraaf.nl/nieuws/2941922/uitlaatgas-kost-samenleving-duizenden-euro-s', 'Haven-Stad wil de gezondheid van de bewoners en werkende mensen verbeteren en willen het motiveren. De luchtvervuiling door auto’s helpt hieraan niet mee, in 2025 moet er 30% minder uitstoot zijn van roet en 35% minder uitstoot van stikstofdioxide. Dit willen we gaan verminderen door slim en schoon vervoer te voorzien in Haven-Stad, zo zijn er milieuzones en wordt elektrisch rijden en het openbaar vervoer gemotiveerd.', '\"Haven-Stad wil de gezondheid van de bewoners en werkende mensen verbeteren en willen het motiveren\"', 'telegraaf.png');

--
-- Indexen voor geëxporteerde tabellen
--

--
-- Indexen voor tabel `articles`
--
ALTER TABLE `articles`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT voor geëxporteerde tabellen
--

--
-- AUTO_INCREMENT voor een tabel `articles`
--
ALTER TABLE `articles`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=61;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
